/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import com.yourcompany.struts.form.NumberForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-29-2013
 * 
 * XDoclet definition:
 * @struts.action path="/number" name="numberForm" input="/ok.jsp" parameter="methodName" scope="request" validate="true"
 * @struts.action-forward name="ok" path="/cal.jsp"
 */
public class NumberAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward doAdd(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		NumberForm numberForm = (NumberForm) form;// TODO Auto-generated method stub
		request.setAttribute("res", numberForm.getNumber1()+numberForm.getNumber2());
		return mapping.findForward("ok");
	}
	
	public ActionForward doMinus(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		NumberForm numberForm = (NumberForm) form;// TODO Auto-generated method stub
		request.setAttribute("res", numberForm.getNumber1()-numberForm.getNumber2());
		return mapping.findForward("ok");
	}
	public ActionForward doMultiply(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		NumberForm numberForm = (NumberForm) form;// TODO Auto-generated method stub
		request.setAttribute("res", numberForm.getNumber1()*numberForm.getNumber2());
		return mapping.findForward("ok");
	}
	public ActionForward doDivision(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		NumberForm numberForm = (NumberForm) form;// TODO Auto-generated method stub
		request.setAttribute("res", numberForm.getNumber1()/numberForm.getNumber2());
		return mapping.findForward("ok");
	}
}