/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 07-29-2013
 * 
 * XDoclet definition:
 * @struts.form name="numberForm"
 */
public class NumberForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** number2 property */
	private Double number2;

	/** number1 property */
	private Double number1;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the number2.
	 * @return Double
	 */
	public Double getNumber2() {
		return number2;
	}

	/** 
	 * Set the number2.
	 * @param number2 The number2 to set
	 */
	public void setNumber2(Double number2) {
		this.number2 = number2;
	}

	/** 
	 * Returns the number1.
	 * @return Double
	 */
	public Double getNumber1() {
		return number1;
	}

	/** 
	 * Set the number1.
	 * @param number1 The number1 to set
	 */
	public void setNumber1(Double number1) {
		this.number1 = number1;
	}
}